'''
    This module provides plotting for pyScaler.   An arbitrary number
    of plotlines can be shown on the same plot.  We are actually
    relatively agnostic about what the data mean.  However the
    rendition of the plot is a strip chart.
'''


#    This software is Copyright by the Board of Trustees of Michigan
#    State University (c) Copyright 2014, 2026
#
#    You may use this software under the terms of the GNU public license
#    (GPL).  The terms of this license are described at:
#
#     http://www.gnu.org/licenses/gpl.txt
#
#	     FRIB
#	     Michigan State University
#	     East Lansing, MI 48824-1321


from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qtagg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure

# 2. Import Qt Widgets dynamically using Matplotlib's compatibility layer
from matplotlib.backends.qt_compat import QtWidgets

# 3. our datasets are data classes:


from typing      import Self

#
#  The plot line colors are selected from these:
#  If there are more plots than the colors listed:
#  1. the graph will be confusing.
#  2. but the colors will cycle back circularly.
#
_COLORS=['black', 'red', 'blue', 'green', 'cyan', 'yellow', 'magenta', 'purple', 'chocolate', 'olive']
_DEFAULT_WINDOW_SIZE=3600              # Default seconds in the plot window.
_DEFAULT_DECIMATION_THRESHOLD=100000   # Max pts before decimation kicks in.
_DEFAULT_DECIMATION_FACTOR=2        # How much decimation is done.


class DataSet:
    '''
        A data set is what can be plotted in a ScalerStripChart.
        Getters for x and y are generated by the decorator above.
    '''
    _t : list[float]
    _y : list[float]
    window : float 
    max_pts : int  
    decimation_factor :int
    
    def __init__(self):
        self._t = []
        self._y = []
        self.window = _DEFAULT_WINDOW_SIZE
        self.max_pts = _DEFAULT_DECIMATION_THRESHOLD
        self.decimation_factor = _DEFAULT_DECIMATION_FACTOR
        
    def t(self) -> list[float]:
        return self._t
    def y(self) -> list[float]:
        return self._y
    
    def decimate(self) -> Self:
        '''
            If there are too many points, decimate those that are
            prior to window of the most recent point:
        '''
        if len(self._t) > self.max_pts:
            now = self._t[-1]
            start = now - window;    # Start time of window.
            
            # Find the first element with time >= start:
            
            last_decimation = next((idx  for idx, item in enumerate(self._t) if item >= start), None)
            if last_decimation is not None:
                reduced_time   = self._t[0:last_decimation:self._decimation_factor]
                reduced_values = self._y[0:last_decimation:self._decimation_factor]
                self._t = reduced_time + self._t[last_decimation:]
                self._y = reduced_values + self._y[last_decimation:]
        return self
    
    def add_point(self, time : float, value : float) -> Self:
        '''
           Add a new point and decimate if needed.
        '''
        
        self._t.append(time)
        self._y.append(value)
        return self.decimate()
    def clear(self):
        self._y = []
        self._t = []
    

class ScalerStripChart(QtWidgets.QWidget):
    '''
        This widget is a stripchart for multiple plotlines.
        Key methods:
        
        * add_plotline(name : str) -> self
            Add a new plotline to the widget.  The color will be chosen by 
            the widget.
              
        * add_point(name : str, seconds : float, value: float) -> self
            Add a time series point to the named plotline.
            Note that if needed the plot is scrolled so that the
            desired time window is maintained.
        * clear() -> self
            Clears all ploints from all plotlines.
        * setWindow(seconds -> int) -> self
            Defines the window of the strip chart.
        * setMaxPoints(max : int) -> self
            Defines the maximum number of points the plotlines can have.  Above this number,
            points to the left of the window are decimated.  Decimation picks every other
            point and removes it from the plot line.
            @todo make the decimation factor settable.
            @note the default decimation with 2 second intervals (the most popular) results in
            an undecimated plot set of 55.5 hours.  This should be adequate for many 
            experiments which usually have run lengths measured in a few hours.
        * plotlines() -> list[str] 
            Returns the list of plot line names
        * window() -> int
            Returns the window size.
        * maxPoints() -> int
            returns the decimation threshold.
        * decimationFactor() -> int
            Returns the decimation factor.  Currently this is hard coded to 2, meaning decimation
            involves removing every other point older than most_recent - window.
        * update()->Self - after a bunch of add_point calls this can be called to update the plot.
    
    '''
    
    def __init__(self, parent = None):
        super().__init__(parent)
        #
        # Make the stuff we need to create the widdget.
        #
        self._figure = Figure(figsize=(5,4), dpi=100)
        self._canvas = FigureCanvas(self._figure)
        self._toolbar = NavigationToolbar(self._canvas, self)
        
        #  Lay it out.
        
        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(self._toolbar)
        layout.addWidget(self._canvas)
        
        self._colorindex = 0     # Next color to select.
        self._windowsize = _DEFAULT_WINDOW_SIZE
        self._maxpts     = _DEFAULT_DECIMATION_THRESHOLD
        self._decimationFactor = _DEFAULT_DECIMATION_FACTOR
        self._maxtime    = 0      # Largest time seen - used to set the x axis range.
        # The data sets are storead as a hash indexed by name containing a hash with the keys:
        # * 'data' - the dataset.
        # * 'color' - the color of the data set.
        # * 'line'  - the line created on the axis for this dataset.
        
        self._plotlines = dict()
        self._axis      = self._figure.add_subplot(111)    # Common axis.
        
        self._canvasDrawn = False                         # Newver did  a draw.
        
        
        
    def add_plotline(self, name : str) -> Self:
        '''
            Add a new named plotline to the chart.
            @param name - the name of the plotline - must be unique
            
        '''
        if name in self._plotlines.keys():
            raise KeyError(f'{name} is already a data set!')
        dataset = {'data' : DataSet(), 
                   'line' : None,
                   'color': self._nextColor()
                }
        self._plotlines[name] = dataset
        return self
    
    def plotlines(self) -> list[str]:
        '''
            @return list[str] - a list of the plot line names.
        '''   
        return self._plotlines.keys()
    
    def clear(self) -> Self:
        '''
            Clear all data sets and the plots:
            
        '''
        for _, value in self._plotlines.items():
            value['data'].clear()
        self._maxtime = 0
        self.update()                  # Update the picture with no data
        
        return self
        
    def add_point(self, name: str, t: float, value: float) -> Self:
        ''''
            Add a point to a data set note this makes no graphical 
            operations.  Those are done in a call to update().
            @param name   - name of the data set.
            @param t      - time value.
            @param value  - Value of the scaler.
            @return self.
            @note  adding a point may trigger decimation.
            @raises IndexError if name is not a data set.
            
        '''
        dataset = self._plotlines[name]
        dataset['data'].add_point(t, value)
        if int(t) > self._maxtime:
            self._maxtime = int(t)                      # update might need to slide.
        return self
    
    def setWindow(self, seconds: int) -> Self:
        '''
            Sets the plot window width.  Once the max t is larger than
            this, the window slides along.
            @param window size in seconds.
            @return self 
            @note   windowsize only visibly changes anything on the next update call.
            @throws  ValueError if seconds <= 0 as that's an obcenity.
        '''
        if seconds <= 0:
            raise ValueError       # Negative window is just wrong.
        self._windowsize = seconds
        
        return self
    
    def window(self) -> int:
        '''
            @return int - the current window size:
        '''
        return self._windowsize
    
    def maxpoints(self) -> int:
        '''
            @return int - the number of points at which decimation kicks in.
        '''        
        return self._maxpts
    
    def setMaxPoints(self, size: int) -> Self:
        self._maxpts = size

    def decimationFactor(self) -> int:
        '''
            @return int - the factor by which data are decimated.
        '''
        return self._decimationFactor
           
    def update(self) -> Self:
        '''
            This is the method that does all of the work.
            For each data set, if it has points but no line,
            plot is called on the axis to produce a line.
            For data sets that have lines, their data are updated.
            Note that if clear() was done, this may lead to plotting an empty line.
            Just for good measure, the legend is updated and the canvas is asked to
            draw (this may be a bad idea mayybe better doen in the constructor if flickering happens?)
        '''
        for name, dataset in self._plotlines.items():
            if dataset['line'] is None:
                # have to add the plot Note plot returns a list of lines, but
                # our list only has one, the command destructures that list.
                
                dataset['line'], = self._axis.plot(
                    dataset['data'].t(), dataset['data'].y(), color=dataset['color'], label=name
                )
            else:
                # plot was already addd, just update the data.
                dataset['line'].set_data(dataset['data'].t(), dataset['data'].y())
            
        # If needed we may have to slide the plot:
        
        if self._maxtime > self._windowsize:
            self._axis.autoscale(axis='y') 
            self._axis.set(xlim=(self._maxtime - self._windowsize, self._maxtime))
        else:
            self._axis.set(xlim=(0, self._windowsize))
            
        
        self._axis.relim()   
        self._axis.autoscale_view(scalex=False, scaley=True)
        self._axis.legend()            # Show which colors mean what.  
        
        if not self._canvasDrawn:
            self._canvas.draw()       # Draw the canvas not done.
            self._canvasDraw = True
            
                
    #   Internal utilities:
    
    def _nextColor(self) -> str:
        # Assign a color:
        
        result = _COLORS[self._colorindex]
        self._colorindex += 1
        return result
            
    
# Test code.

if __name__ == "__main__":
    from matplotlib.backends.qt_compat import QtCore

    import math
    time  = 0     # Seonds into simulated run....
    
    
    def update():
        global time
        window.add_point(
            'scaler1', time, abs(100.0*math.sin(time/(4.0*3.1416)))).add_point(
            'scaler2', time, abs(50.0*math.cos(time/(2.0*3.1416)))).update()
        time += 2
    def setupPlotting():

        window.add_plotline('scaler1')
        window.add_plotline('scaler2')
        window.setWindow(60)     # Narrow window so scrollinbg happens soon.
        
        
        
    import sys
    app = QtWidgets.QApplication(sys.argv)
    
    # Create the custom widget and show it
    window = ScalerStripChart()
    
    setupPlotting()
    # Set up to add points every two seconds.
        
    timer = QtCore.QTimer()
    
    timer.setSingleShot(False)    # repeat.
    timer.timeout.connect(update)
    timer.start(2000)
    
    window.setWindowTitle("Matplotlib in QWidget")
    window.resize(800, 600)
    window.show()
    
    sys.exit(app.exec())