


SUBDIRS = 				common	\
					daqstart \
					dvdburn \
					sequencer \
                                        Buffer \
                                        format \
					FormattedIO \
					filter \
					conversion \
					ringselector \
					eventlog \
					bufdump	\
					sclclient \
					tkbufdump \
					compatibility \
					newscaler	\
					pyscaler \
					fileanalyzer	\
                                        scalerReader \
					scalersum reglom  \
					swtrigger \
					logbook \
					manager \
					readoutREST \
					udpBroker \
					ringdiagnostics \
					managercontrol \
					statsview \
					s800scalers

# scalerdisplay - removed in favor of newscaler

