#    This software is Copyright by the Board of Trustees of Michigan
#    State University (c) Copyright 2014, 2026
#
#    You may use this software under the terms of the GNU public license
#    (GPL).  The terms of this license are described at:
#
#     http://www.gnu.org/licenses/gpl.txt
#
#	     FRIB
#	     Michigan State University
#	     East Lansing, MI 48824-1321

'''
    @file LogBookUIUtilities.py
    @brief Reusable GUI Utilities for the lg_xxx.py programs.
    @author Ron Fox
    @note See individual class and method docstrings for more information.
'''


import os
import pathlib
import subprocess
import sys
from collections.abc import Iterable
from datetime import datetime
from tempfile import NamedTemporaryFile
import time

from nscldaq.editablelist6 import ListToListEditor
from nscldaq.LogBook import LogBook
from nscldaq.mg_configutils import OkDialog
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import (
    QComboBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QMessageBox,
    QVBoxLayout,
    QWidget,
)

TEMPDIR = pathlib.Path('~/.nscl-logbook').expanduser().absolute()  

tmpFileIndex : int = 0

def timestring(stamp : int) -> str: 
    '''
     Convert a unix timestamp in to a time string in the current zone.
    '''
    
    timestamp = datetime.fromtimestamp(  # noqa: DTZ006
        stamp, tz=None
    )                                                  # in local time.
    return  timestamp.strftime('%c')

def makeNoteHtmlFilename(id : int) -> str:
    '''
    Create the full path to the HTML filename for a note.  This is pretty well
    ensured to be unique
    '''
    global tmpFileIndex
    tmpFileIndex += 1
    note_path = TEMPDIR / f'note-{id}-{int(time.time())}-{os.getpid()}-{tmpFileIndex}.html'
    return str(note_path)

def programPath(name :str) -> str | None:
    '''
        Generate the full path to a program in DAQBIN.
        @param name - name of the program.
        @return str program path.
        @retval None - DAQBIN is not defined or $DAQBIN/name does not exist.
             in both of those cases a QMessageBox.Warningi s popped up.
    '''
    if 'DAQBIN' not in os.environ:
        QMessageBox.warning(
            None, 'DAQBIN undefined', 
            'The "DAQBIN" environment variable is not defined, use a daqsetup.bash script to define it.'
        )
        return None
    path = pathlib.Path(os.environ['DAQBIN']) / name
    if not path.exists():
        QMessageBox.warning(
            None,'No Such executable', 
            f'There is no executable named {name} in $DAQBIN'
        )
        return None
    return str(path)
    
    
def generateMarkdownFromItemList(items : list[LogBook.Run | LogBook.Transition | LogBook.Note]) -> str:
    '''
    Given a list of logbook items, returns the markdown rendering of all of them as a single string
    that can be passed to pandoc for rendering into a usable form (HTML or PDF).
    @param items : list[LogBook.Run | LogBook.Transition | LogBook.Note] 
            - The list of items to render sequentially.
    @return str  - the string of markdown.
    
    '''
    result = ''
    for item in items:
        match type(item):
            case LogBook.Run:
                result += genRunHeaderMarkdown(item)
            case LogBook.Transition:
                result += genTransitionMarkdown(item)
            case LogBook.Note:
                result += genNoteMarkdown(item)
            
    return result

def genRunHeaderMarkdown(run : LogBook.Run) -> str:
    '''
        Generate  the markdown for a run header.  Note the
        transition markdown is generated by genTranstionMarkdown below.

        @param run : LogBook.Run - the run object to render.
        @return str the Markdown rendering of the run.
        
        The run header is rendered as a level 2 header with the run number
        and a title.
    '''
    
    return f"## Run {run.number} : {run.title}\n\n"

def genTransitionMarkdown(transition : LogBook.Transition) -> str:
    '''
        Generates the markdown for a run state transition.
        
        @param transition - the transition object.
        @return str       - the markdown for the transition.
        
        The transition is rendered as a timestamped run transition name
        Followed by any transition remark.  Below all that is the name
        of the shift active during the transition and the names of the
        people assigned to that shift (as a table).
        
    '''
    result = f"\n\n### Run Transition; {transition.transition_name} at: {timestring(transition.time)}\n\n"
    result += transition.comment + "\n\n"
    
    shift = transition.shift
    result += f"\n\nShift: {shift.name}\n\n"
    result += "| Shift Members|\n"
    result+=  "|--------------|\n"
    for member in shift.members:
        result += f"| {personName(member)} |\n"
    
    result += "\n\n"    
    return result
    
    

def genNoteMarkdown(note : LogBook.Note) -> str:
    '''
        Given a note, generate the valid HTML for it with images exported
        and fixed up.
        
        @param note - a logbook note object.
        @return str - the full valid markdown.
    '''
    
    note_contents = note.substitute_images()   # Images exported and links fixed up.
    
    # compute and prepend the header that the Tcl stuff used to add:
    
    whenWritten = timestring(note.time)
    author      = personName(note.author)
    
    header_text = f'''
    
### Note:

|Item | Value |
|-----|-------|
|Author | {author} |
| Written | {whenWritten} |'''
    if note.run is not None:
        run = note.run
        header_text += f'''
| For Run: | {run.number} |
| Title:   | {run.title}  |
| Started  | `{timestring(run.get_transition(0).time)}` |'''
        if not run.is_active():
            lastIndex = run.transition_count() - 1
            header_text += f'''
| Ended | `{timestring(run.get_transition(lastIndex).time)}` |'''
        else:
            header_text += '''| Still active | |'''
    full_text = header_text + '\n\n' +note_contents + '\n\n'
    return full_text


def markdownToHtml(markdown: str, outFile: str) -> None:
    ''''
        Puts the input text in a temporary file, and runs pandoc on it to 
        produce html in the outputFile:
        
        @param inputText - The markdown to create.
        @param outFile   - The name of the file into which the html shoulid be written.
    
        @note assumes pandoc is installed and in the path.
    '''  
    
    pandoc = subprocess.Popen([
        'pandoc',
        '-f', 'markdown+link_attributes+backtick_code_blocks', 
        '-t', 'html',
        '-o', outFile],
        stdin = subprocess.PIPE, encoding='utf-8'
    )     
    out, err = pandoc.communicate(markdown)
    if out is not None:
        print('Pandoc output: ', out)
    if err is not None:
        print('Pandoc error:', err)

def markdownToPdf(markdown : str, outFile : str) -> None:
    ''''
        Generate a PDF file from markdown:
        @param markdown - the mardown text
        @param outfile  - Path to the output file.
    
    '''
    pandoc = subprocess.Popen([
        'pandoc',
        '-f', 'markdown+link_attributes+backtick_code_blocks', 
        '-t', 'pdf',
        '-o', outFile], 
        stdin = subprocess.PIPE, encoding='utf-8')
    
    out,err = pandoc.communicate(markdown)
    if out is not None:
        print('pandoc output', out)
    if err is not None:
        print('pandoc errors', err)
                

def personName(person : LogBook.Person) -> str:
    '''
        Creat the standard name 'salutation firstname lastname' from 
        a person.
    '''
    return f'{person.salutation} {person.firstname} {person.lastname}'

class ShiftMemberEditor(ListToListEditor):
    '''
        Provides an editor of shift membership
        that is based on the list to list editor. The differences
        are that elements of each list are derived from LogBook.Person lists
        rather than textual lists
        
        We'll do this by holding a map of tuples -> Person objects.
        where the tuples are used to derive the contents of the 
        listboxes and discover the people in each listbox.
        
        Attributes:
          nonMembers - list of LogBook.Person that are not in the shift
          members    - list of LogBook.Person that are in the shift
          
    '''
    def __init__(self, *args):
        super().__init__(*args)
    
        # These are hashes of LogBook.Person
        # Keyed by the (lastname, firstname, salutation) tuple.
    
        self._members = {}    
        self._nonmembers = {}
        
    # Attributes:
    
    def members(self) -> list[LogBook.Person]:
        self._reconstructDicts()
        return list(self._members.values())     # Want an actual list not a view.
    def setMembers(self, members : list[LogBook.Person]) -> None:
        member_list = self.selectedbox().listbox()   # QListWidget 
        self._members = self._setHashAndListBox(member_list, members)
        
    
    def nonMembers(self) -> list[LogBook.Person]:
        self._reconstructDicts()
        return list(self._nonmembers.values())
    
    def setNonMembers(self, nonmembers : list[LogBook.Person]):
        nonmember_list = self.sourcebox()
        self._nonmembers = self._setHashAndListBox(nonmember_list, nonmembers)
        
        
    def _setHashAndListBox(
        self, 
        listbox : QListWidget, people : list[LogBook.Person]) -> dict[(str, str, str), LogBook.Person]:
        #  Given a listbox and a list of people, construct the dict hash of the people and fill the
        # listbox with salutation firstname, lastname.
        
        listbox.clear()
        result : dict[(str,str,str), LogBook.Person] = {}
        
        for person in people:
            lastname = person.lastname
            firstname = person.firstname
            salutation = person.salutation
            result[(lastname, firstname, salutation)] = person
            
            item = personName(person)
            listbox.addItem(item)
        
        return result
        
    def _reconstructDicts(self) -> None:
        # Since we have no signals to keep the dicts updated, we
        # need to reconstruct them when asked for the contents:
        
        memberstuples = self._listboxToTuples(self.selectedbox().listbox())
        nonmembertuples = self._listboxToTuples(self.sourcebox())
        
        members = {}
        nonmembers = {}
        
        # Build the members hash:
        
        for member_tuple in memberstuples:
            if member_tuple in self._members:
                members[member_tuple] = self._members[member_tuple]
            else:
                members[member_tuple] = self._nonmembers[member_tuple]
    
        # build the nonmembers hash:
        
        for nonmember_tuple in nonmembertuples:
            if nonmember_tuple in self._members:
                nonmembers[nonmember_tuple] = self._members[nonmember_tuple]
            else:
                nonmembers[nonmember_tuple] = self._nonmembers[nonmember_tuple]
            
        # NOw set the attribute data:
        
        self._members = members
        self._nonmembers = nonmembers
        
    def _listboxToTuples(self, listbox : QListWidget) -> list[tuple[str, str, str]]:
        # Turn the contents of a listbox widget into lastname, salutation tuples:
        
        result = []
        for row in range(listbox.count()):
            rowtext = listbox.item(row).text()
            (salutation, firstname, lastname) = rowtext.split(' ')
            result.append((lastname, firstname, salutation))
        return result

class ShiftCreator(QWidget):
    '''
    Provides a work area for creating a shift:
    
    '''
    def __init__(self, parent : QWidget | None = None):
        super().__init__(parent)
        
        self._layout = QVBoxLayout()
        self.setLayout(self._layout)
        
        # Top bit is the prompt for the shiftname and line edit for it:
        
        namelayout = QHBoxLayout()
        namelayout.addWidget(QLabel('Shift Name: ', self))
        self._name = QLineEdit(self)
        namelayout.addWidget(self._name)
        
        self._layout.addLayout(namelayout)
        
        #  Now the shift editor:
        
        self._memberEditor = ShiftMemberEditor(self)
        self._layout.addWidget(self._memberEditor)
       
    def name(self) -> str:
        '''
            @return str - the shfit name.
        '''
        
        return self._name.text()
    
    
    
    def setPeople(self, people : list[LogBook.Person]) -> None:
        '''
            @param people : list[LogBook.Person] - People known to the logbook.
        '''
        
        self._memberEditor.setNonMembers(people)
    def getMembers(self) -> list[LogBook.Person]:
        '''
        @return list[LogBook.Person] - List of the people on the shift.
        '''
        return self._memberEditor.members()                

class ShiftEditor(QWidget):
    '''
        Edit the members of an existing shift.  This is very much like
        ShiftCreator but 
        1. The name of the shift is just a label and can't be changed.
        2. We fully expose the ShiftMemberEditor subwidget.
        
    '''
    def __init__(self, parent : QWidget | None = None) :
        super().__init__(parent = parent)
        
        self._layout = QVBoxLayout()
        self.setLayout(self._layout)
        
        namelayout = QHBoxLayout()
        namelayout.addWidget(QLabel('Shift:', self))
        self._name = QLabel(self)
        namelayout.addWidget(self._name)
        
        self._layout.addLayout(namelayout)
        
        self._memberEditor = ShiftMemberEditor(self)
        self._layout.addWidget(self._memberEditor)
        
    def editor(self) -> ShiftMemberEditor:
        '''
        @return ShiftMemberEditor - our editor widget.
        '''
        return self._memberEditor
    def name(self) -> str:
        '''
        @return str - the shift name
        '''
        return self._name.text()
    def setName(self, name :str) -> None:
        '''
        @param name : str - shift name string
        '''
        self._name.setText(name)
        
        
class ShiftChooser(QWidget):
    '''
        Provides a chooser for shifts.
    '''
    shiftselected = pyqtSignal(str)
    
    def __init__(self, parent : QWidget  | None = None):
        super().__init__(parent)
        self._layout = QVBoxLayout()
        self._layout.addWidget(QLabel('Choose Shift: ', self))
        self.setLayout(self._layout)
        
        self._shifts = QComboBox(self)
        self._layout.addWidget(self._shifts)
        self._shifts.currentTextChanged.connect(self.shiftselected)
        
    def setShifts(self, shifts : Iterable[str]) -> None:
        '''
        @param shifts :Iterable[str] - Available shifts to select from.
        '''
        self._shifts.clear()     # Clear any prior one.
        for shift in shifts:
            self._shifts.addItem(shift)
    
    def shift(self) -> str:
        '''
        @return str - the currently selected shift.
        '''
        
        return self._shifts.currentText()

class ShiftChooserDialog(OkDialog):
    '''
    Ok dialog that wraps a ShiftChooser workarea
    '''
    
    def __init__(self, parent : None |QWidget = None):
        super().__init__(ShiftChooser(), parent = parent)        
    
class PersonChooser(QComboBox):
    '''
        Select a person (e.g. note author)
        
        Attributes:
        setPeople - Sets the people you can select from.
        selected   - Returns the selected person.
    '''
    def __init__(self, parent : QWidget | None = None):
        super().__init__(parent)
        self._people : Iterable[LogBook.Person] | None = None

    def setPeople(self, people : Iterable[LogBook.Person]) -> None:
        '''
            Set the combobox to the possible people to select from:
            @param people : Iterable[LogBook.Person] - The people to choose from.
        '''
        
        self.clear()
        self._people = people
        for person in people:
            name = self._makeNameString(person)
            self.addItem(name)
    
    def selected(self) -> LogBook.Person | None:
        '''
        @return LogBook.Person | None - The selected person.  
        @retval None - can only be returned if there are no peple to select as
                       if QComboBox has choices, one will always be current.
        '''
        name = self.currentText()
        if not name:
            return None
        for person in self._people:
            if name == self._makeNameString(person):
                return person
        
        raise AssertionError('PersonChooser.selected - could not match the name!!')

    # Utility private methods:
    
    def _makeNameString(self, person : LogBook.Person) -> str:
        return personName(person)      # Factored out.
        
        
class RunChooser(QComboBox):
    '''
        Select a run... This chooser also holds an empty slot to allow
        no run to be selected. Note the runs are listed in reverse sort order
        (large to small) because most likely a user will be selecting a recent
        (large) run number.
        
        Methods:
           setRuns  - Sets the possible runs.
           selectedRun - Returns the selected run.
    '''
    def __init__(self, parent : QWidget | None = None):
        super().__init__(parent)
        self._runs : Iterable[LogBook.Run] | None = None

        
    def setRuns(self, runs : Iterable[LogBook.Run]) -> None:
        '''
            Sets the combobox. with the runs that can be selected.
            Note there's always an empty first element.
            
            @param runs Iterable[LogBook.Run] - the choosable runs.
            @note the combobox will be ordered from large to small run numbers.
        '''
        
        self._runs = runs
        self.clear()
        self.addItem('')    # No run selected.
        sorted_runs = sorted(runs, key=lambda r: r.number, reverse=True)
        for r in sorted_runs:
            self.addItem(f'{r.number} {r.title}')
            
        
    def selectedRun(self) -> LogBook.Run | None:
        '''
            @return LogBook.Run | None - The run that was selected or None if none was selected.
        '''
        run_text = self.currentText()
        if not run_text:
            return None
        run_number = int(run_text.split(' ')[0])   # The number of the selected run.
        for  r in self._runs:
            if r.number == run_number:
                return r
        
        raise AssertionError(f'RunChooser.selectedRun found no match for {run_text}')
        
        
        