#
#  usb/vmusb/sis3316examples: Struck's SIS3316 example programs, installed
#  in ${prefix}/sis3316.
#

add_subdirectory(rebootall)
add_subdirectory(ch1_to_ch16_external_trigger_test)
add_subdirectory(internaltrigger_externalgate_dt)
add_subdirectory(intclk_onemodule)
add_subdirectory(FPBUS_threads_allmodules)
add_subdirectory(FPBUS_read_temps)
add_subdirectory(FPBUS_external_trigger)
add_subdirectory(FPBUS_appl_allmods)
add_subdirectory(register_rw)
add_subdirectory(fwupdate)
add_subdirectory(access_rate)
add_subdirectory(rootgui)
add_subdirectory(inventory)
