#  Arjen's Plotchart 2.0 (provisional) -> TclLibs/plotchart.

install(PROGRAMS pkgIndex.tcl xyplot.tcl plotanim.tcl plotannot.tcl plotaxis.tcl
    plotbind.tcl plotbusiness.tcl plotchart.tcl plotcombined.tcl plotconfig.tcl
    plotcontour.tcl plotgantt.tcl plotobject.tcl plotpack.tcl plotpriv.tcl
    plotscada.tcl plotspecial.tcl plot3d.tcl plottable.tcl scaling.tcl
  DESTINATION TclLibs/plotchart)
