#  This package provides a ring buffer performance
# monitor.  It is intended to be started at system start
# time though it can be started manually.
# It will advertise the service RING_MONITOR
# With the port manager.  I've not decided if it'll
# be a web server or if there will be a display client 
# component (perhaps pyqt).  We'll see 
[package]
name = "ring_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
portman_client = "0.2.0"
ringmaster_client = "0.1.1"
nscldaq_ringbuffer = "0.8.7"
rust_ringitem_format = "0.1.2"
serde_json = "1.0.143"