add_subdirectory(pugi)
add_subdirectory(iniparser)
add_subdirectory(factories)
add_subdirectory(thread)
add_subdirectory(os)
add_subdirectory(CopyrightTools)
add_subdirectory(cvt)
add_subdirectory(uri)
add_subdirectory(headers)
add_subdirectory(tclwidgets)
add_subdirectory(security)
add_subdirectory(tcpip)
add_subdirectory(plotchart)
add_subdirectory(bltsubst)
add_subdirectory(plotcontainer)
add_subdirectory(tclutils)
add_subdirectory(testutils)
add_subdirectory(sqliteplus)
add_subdirectory(udp)
