bin_PROGRAMS=sis3316_rebootall

sis3316_rebootall_SOURCES=sis3316_class.cpp \
sis3316_ethernet_access_class.cpp \
sis3316_reboot_all_modules.cpp

noinst_HEADERS=project_interface_define.h  \
    sis3316_ethernet_access_class.h \
    project_system_define.h     \
    sis3316.h \
    sis3316_class.h             \
    vme_interface_class.h