name: 12.0-maint workflow

on:
  push:
    branches: [ "12.0-maint" ]

jobs:
  buster:
    uses: ./.github/workflows/build.yml
    with:
      os-version: buster
      packaging: true
    secrets: inherit
  bullseye:
    uses: ./.github/workflows/build.yml
    with:
      os-version: bullseye
      packaging: true
    secrets: inherit
