name: Compiling workflow

on:
  push:
    branches: 
      - '12.0-maint'
      - '12.1-dev'
    tags:
      - '*'

jobs:
  buster:
    uses: ./.github/workflows/build.yml
    with:
      os-version: buster
      packaging: startsWith(github.ref, 'refs/tags/v')
    secrets: inherit
  bullseye:
    uses: ./.github/workflows/build.yml
    with:
      os-version: bullseye
      packaging: startsWith(github.ref, 'refs/tags/v')
    secrets: inherit
