name: Compiling workflow

on:
  push:
    branches: 
      - '12.1-srs'
    tags:
      - '*'
    paths-ignore:
      - 'release_notes'
      - '**.md'
      - '**/README'
      - '**/NEWS'
      - '**/AUTHORS'
      - '**/COPYING'
      - '**/INSTALL'
      - '**/ChangeLog'

jobs:
#  buster:
#     uses: ./.github/workflows/build.yml
#     with:
#       os-version: buster
#       packaging: true
#       dist-packaging: ${{ startsWith(github.ref, 'refs/tags') }}
#     secrets: inherit
  bullseye:
    uses: ./.github/workflows/build.yml
    with:
      os-version: bullseye
      packaging: true
      dist-packaging: ${{ startsWith(github.ref, 'refs/tags') }}
    secrets: inherit
  release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    needs: [bullseye]
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ github.ref_name }}
