name: Compiling workflow

on:
  push:
    branches: 
      - '12.0-maint'
    tags:
      - '*'
    paths-ignore:
      - 'release_notes'
      - '**.md'
      - '**/README'
      - '**/NEWS'
      - '**/AUTHORS'
      - '**/COPYING'
      - '**/INSTALL'
      - '**/ChangeLog'

jobs:
  buster:
    uses: ./.github/workflows/build.yml
    with:
      os-version: buster
      packaging: true
      dist-packaging: ${{ startsWith(github.ref, 'refs/tags') }}
    secrets: inherit
  bullseye:
    uses: ./.github/workflows/build.yml
    with:
      os-version: bullseye
      packaging: true
    secrets: inherit
  release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    needs: [buster, bullseye]
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ github.ref_name }}
