name: 12.0-maint workflow

on:
  push:
    branches: [ "12.0-maint" ]

jobs:
  buster-build:
    uses: ./.github/workflows/build.yml
    with:
      os-version: buster
      packaging: false
  bullseye-build:
    uses: ./.github/workflows/build.yml
    with:
      os-version: bullseye
      packaging: false
