name: 12.0-maint workflow
on:
  push:
    branches: [ "12.0-maint" ]
jobs:
  buster-packaging-job:
    runs-on: ubuntu-latest
    container:
      image: fribdaq/frib-buster-ci:v3.9
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: autoreconf
        working-directory: ./main
        run: autoreconf -if
      - name: Configure tcl++
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        working-directory: ./main
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          eval `ssh-agent -s`
          
          echo "${{ secrets.LIBTCLPLUS }}" | ssh-add -
          ./tcl++incorp
          ssh-add -D
          
          eval `ssh-agent -k`
      - name: Incorporate unified format
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        working-directory: ./main
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          eval `ssh-agent -s`
          
          echo "${{ secrets.UNIFIEDFMT }}" | ssh-add -
          ./unifiedfmt-incorp.sh
          ssh-add -D
          
          eval `ssh-agent -k`
      - name: Creating build directory
        run: mkdir main/oot
      - name: Configuring
        working-directory: ./main/oot
        shell: bash
        run: |
          ../configure --prefix=$PWD/install \
                       --enable-usb=yes \
                       --enable-caen-digitizer-support \
                       --enable-docs \
                       --enable-epics-tools=yes \
                       --with-caen-digitizer-libroot=/usr/opt/caendigitizerlibs \
                       --with-epics-rootdir=/usr/opt/epics \
                       --enable-ddas=yes \
                       --with-xiaapidir=/usr/opt/xiaapi/2.13.0 \
                       --with-plx-sdk=/usr/opt/plx \
                       --with-firmwaredir=/usr/opt/ddas/firmware/2.1-000/firmware \
                       --with-dspdir=/usr/opt/ddas/firmware/2.1-000/dsp \
                       --with-rootsys=/usr/opt/root/root-6.24.06 \
                       CXX=/usr/opt/mpi/openmpi-4.0.1/bin/mpicxx
      - name: Make
        working-directory: ./main/oot
        run: make -j2 clean && make -j2 all && make -j2 install
  bullseye-packaging-job:
    runs-on: ubuntu-latest
    container:
      image: fribdaq/frib-bullseye-ci:v1.7
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: autoreconf
        working-directory: ./main
        run: autoreconf -if
      - name: Configure tcl++
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        working-directory: ./main
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          eval `ssh-agent -s`
          
          echo "${{ secrets.LIBTCLPLUS }}" | ssh-add -
          ./tcl++incorp
          ssh-add -D
          
          eval `ssh-agent -k`
      - name: Incorporate unified format
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        working-directory: ./main
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          eval `ssh-agent -s`
          
          echo "${{ secrets.UNIFIEDFMT }}" | ssh-add -
          ./unifiedfmt-incorp.sh
          ssh-add -D
          
          eval `ssh-agent -k`
      - name: Creating build directory
        run: mkdir main/oot
      - name: Configuring
        working-directory: ./main/oot
        shell: bash
        run: |
          ../configure --prefix=$PWD/install \
                       --enable-usb=yes \
                       --enable-caen-digitizer-support \
                       --enable-docs \
                       --enable-epics-tools=yes \
                       --with-caen-digitizer-libroot=/usr/opt/caendigitizerlibs \
                       --with-epics-rootdir=/usr/opt/epics \
                       --enable-ddas=yes \
                       --with-xiaapidir=/usr/opt/xiaapi/2.13.0 \
                       --with-plx-sdk=/usr/opt/plx \
                       --with-firmwaredir=/usr/opt/ddas/firmware/2.1-000/firmware \
                       --with-dspdir=/usr/opt/ddas/firmware/2.1-000/dsp \
                       --with-rootsys=/usr/opt/root/root-6.24.06 \
                       CXX=/usr/opt/mpi/openmpi-4.1.4/bin/mpicxx
      - name: Make
        working-directory: ./main/oot
        run: make -j2 clean && make -j2 all && make -j2 install
