name: Release packages

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  release-packages:
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Move all files into one place
        run: | 
          ls
          ls *
          mv */*/*.tar.gz .
      - name: Cloneing the repository
        uses: actions/checkout@v3
      - name: Extract release note
        run: ./extract_release_note.sh ${{ inputs.tag }}
      - name: Create a release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ./*.tar.gz
          name: Relase of ${{ inputs.tag }}
          body_path: release_body
